name: "Deleting the Infrastructure of Kool Form Production"

on:
  workflow_dispatch:
    inputs:

      confirm_destroy:
        description: "Please Confirm the Deletion of Your Infrastructure"
        required: true
        type: choice
        options:
          - "yes"
          - "no"

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: "Repository Checkout"
        uses: actions/checkout@v4

      - name: "Terraform Setup"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: "Terraform Init"
        run: terraform init
        working-directory: ./terraform/

      - name: "Terraform Destroy"
        if: ${{ github.event.inputs.confirm_destroy == 'yes' }}
        run: terraform destroy -auto-approve
        working-directory: ./terraform/
